### ISSUE TITLE
The list of  nb_neurons

### ISSUE THREAD

**Issue by Jumpleoleoleo** [jliphard/DeepEvolve#6] opened 2018-11-12 13:08 UTC
Hi,
i got the result like INFO - {'activation': 'relu', 'nb_layers': 2, 'optimizer': 'nadam', 'nb_neurons': [64, 64, 16, 16, 16, 128]}
Why the list of nb_neurons has six numbers (i mean, there is two nb_layers)?

**Comment by SaumyaTiwari01** [comment] 2018-11-13 20:21
See this code snippet: 
`
for i in range(0,nb_layers):
        # Need input shape for first layer.
        if i == 0:
            model.add(Conv2D(nb_neurons[i], kernel_size = (3, 3), activation = activation, padding='same', input_shape = input_shape))
        else:
            model.add(Conv2D(nb_neurons[i], kernel_size = (3, 3), activation = activation))
        `
So if you have two nb_layers, take the first two nb_neurons and disregard the rest. So for this case it would be 64 and 64 for first and second layer respectively.

**Comment by Jumpleoleoleo** [comment] 2018-11-14 07:17
Thank you so much for your reply.

**Comment by gndowns** [comment] 2018-11-15 05:35
@jliphard @Jumpleoleoleo I think we can close this and mark it resolved? This is the intended behaviour as explained by @SaumyaTiwari01.

**Closed as completed** 2018-11-15 06:07 UTC
